spring.application.name=consumer-service

server.port=8081


kafka-consumer-config.group-id=requestHandler-group-1
kafka-consumer-config.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka-consumer-config.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
kafka-consumer-config.trusted-packages=*
