spring.application.name=consumer-service

server.port=8081

spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


kafka-consumer-config.group-id=requestHandler-group-1
kafka-consumer-config.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka-consumer-config.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
kafka-consumer-config.trusted-packages=*
#LATEST: START FROM LATEST MESSAGES IN THE QUEUE. EARLIEST: READ ALL HISTORY OF MESSEGUES ON QUEUE
kafka-consumer-config.auto-offset-reset=latest
kafka-consumer-config.listener-concurrency=1