x-kafka-common: &kafka-common
  image: confluentinc/cp-kafka:7.7.8
  environment: &kafka-common-env
    KAFKA_KRAFT_MODE: 'true'
    CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDM2Qk"
    KAFKA_PROCESS_ROLES: controller,broker
    KAFKA_CONTROLLER_QUORUM_VOTERS: >-
      1@webhook-handler-kafka-kafka1:9093,
      2@webhook-handler-kafka-kafka2:9093,
      3@webhook-handler-kafka-kafka3:9093
#        node@url
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
    KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
    KAFKA_LOG_DIRS: /tmp/kafka-vol-logs
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    KAFKA_LOG_RETENTION_HOURS: 168
    KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  networks:
    - webhook-handler-network

x-common-backend: &common-backend
  environment: &common-backend-env
    ACTIVE_PROFILE: default
    MYSQL_USER: user
    MYSQL_PASSWORD: pass
    MYSQL_URL: jdbc:mysql://webhook-handler-db-mysql:3306/webhookHandlerDB
  depends_on:
    db-mysql:
      condition: service_healthy
    init-kafka:
      condition: service_completed_successfully
  networks:
    - webhook-handler-network


services:
  db-mysql:
    image: mysql:8.4
    container_name: webhook-handler-db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: webhookHandlerDB
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppass"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - webhook-handler-network


  kafka1:
    <<: *kafka-common
    container_name: webhook-handler-kafka-kafka1
    environment:
      <<: *kafka-common-env
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: webhook-handler-kafka-kafka1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://webhook-handler-kafka-kafka1:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
    ports:
      - 9092:9092
    volumes:
      - kafka-vol-1:/var/lib/kafka/data
  kafka2:
    <<: *kafka-common
    container_name: webhook-handler-kafka-kafka2
    environment:
      <<: *kafka-common-env
      KAFKA_NODE_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: webhook-handler-kafka-kafka2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://webhook-handler-kafka-kafka2:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
    ports:
      - 9094:9092
    volumes:
      - kafka-vol-2:/var/lib/kafka/data
  kafka3:
    <<: *kafka-common
    container_name: webhook-handler-kafka-kafka3
    environment:
      <<: *kafka-common-env
      KAFKA_NODE_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: webhook-handler-kafka-kafka3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://webhook-handler-kafka-kafka3:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
    ports:
      - 9096:9092
    volumes:
      - kafka-vol-3:/var/lib/kafka/data
  init-kafka:
    <<: *kafka-common
    container_name: webhook-handler-kafka-init
    environment:
      KAFKA_BOOTSTRAP_SERVERS: webhook-handler-kafka-kafka1:9092,webhook-handler-kafka-kafka2:9092,webhook-handler-kafka-kafka3:9092
      KAFKA_REPLICATION_FACTOR: 3
      KAFKA_MAX_RETRIES: 30
      KAFKA_RETRY_INTERVAL: 5
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      
      # block until kafka is reachable
      until kafka-topics.sh --bootstrap-server $$KAFKA_BOOTSTRAP_SERVERS --list > /dev/null 2>&1; do
        echo "Waiting for Kafka..."; sleep 5
      done
      
      echo -e 'Deleting kafka topics'
      kafka-topics.sh --bootstrap-server $$KAFKA_BOOTSTRAP_SERVERS --topic webhook-topic --delete --if-exists
      
      echo -e 'Creating kafka topics'
      kafka-topics.sh --bootstrap-server $$KAFKA_BOOTSTRAP_SERVERS --create --if-not-exists --topic webhook-topic --replication-factor 3 --partitions 3

      echo -e 'Successfully created the following topics:'
      kafka-topics.sh --bootstrap-server $$KAFKA_BOOTSTRAP_SERVERS --list

    depends_on:
      kafka1:
        condition: service_started
      kafka2:
        condition: service_started
      kafka3:
        condition: service_started
    networks:
      - webhook-handler-network

  request-handler-backend:
    <<: *common-backend
    build:
      context: .
      dockerfile: ./requestHandler-service/Dockerfile
    container_name: webhook-handler-request-handler-backend
    environment:
      <<: *common-backend-env
      KAFKA_CONFIG_BOOTSTRAP_SERVERS: >-
        webhook-handler-kafka-kafka1:9092,
        webhook-handler-kafka-kafka2:9092,
        webhook-handler-kafka-kafka3:9092
    ports:
      - "8080:8080"

  consumer-backend:
    <<: *common-backend
    build:
      context: .
      dockerfile: ./consumer-service/Dockerfile
    container_name: webhook-handler-consumer-backend
    environment:
      <<: *common-backend-env
      KAFKA_CONFIG_BOOTSTRAP_SERVERS: >-
        webhook-handler-kafka-kafka1:9092,
        webhook-handler-kafka-kafka2:9092,
        webhook-handler-kafka-kafka3:9092
    ports:
      - "9090-9095:8081"


volumes:
  kafka-vol-1:
  kafka-vol-2:
  kafka-vol-3:
#  db-mysql-vol:

networks:
  webhook-handler-network:
    driver: bridge