x-kafka-common: &kafka-common
  image: confluentinc/cp-kafka:7.7.8
  environment: &kafka-common-env
    KAFKA_KRAFT_MODE: 'true'
    CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDM2Qk"
    KAFKA_PROCESS_ROLES: controller,broker
    KAFKA_CONTROLLER_QUORUM_VOTERS: 1@webhook-handler-kafka-kafka1:9093  # node@url
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
    KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
    KAFKA_LOG_DIRS: /tmp/kafka-vol-logs
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    KAFKA_LOG_RETENTION_HOURS: 168
    KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  volumes:
    - kafka-vol:/var/lib/kafka/data
  networks:
    - webhook-handler-network

x-common-backend: &common-backend
  environment: &common-backend-env
    ACTIVE_PROFILE: default
    MYSQL_USER: user
    MYSQL_PASSWORD: pass
    MYSQL_URL: jdbc:mysql://webhook-handler-db-mysql:3306/webhookHandlerDB
  depends_on:
    db-mysql:
      condition: service_healthy
    kafka1:
      condition: service_started
  networks:
    - webhook-handler-network


services:
  db-mysql:
    image: mysql:8.4
    container_name: webhook-handler-db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: webhookHandlerDB
    ports:
      - "3306:3306"
    networks:
      - webhook-handler-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppass"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  kafka1:
    <<: *kafka-common
    container_name: webhook-handler-kafka-kafka1
    environment:
      <<: *kafka-common-env
      KAFKA_ADVERTISED_HOST_NAME: webhook-handler-kafka-kafka1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://webhook-handler-kafka-kafka1:9092
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
    ports:
      - 9092:9092


  request-handler-backend:
    <<: *common-backend
    build:
      context: .
      dockerfile: ./requestHandler-service/Dockerfile
    container_name: webhook-handler-request-handler-backend
    environment:
      <<: *common-backend-env
      KAFKA_CONFIG_BOOTSTRAP_SERVERS: webhook-handler-kafka-kafka1:9092
    ports:
      - "8080:8080"

  consumer-backend:
    <<: *common-backend
    build:
      context: .
      dockerfile: ./consumer-service/Dockerfile
    container_name: webhook-handler-consumer-backend
    environment:
      <<: *common-backend-env
      KAFKA_CONFIG_BOOTSTRAP_SERVERS: webhook-handler-kafka-kafka1:9092
    ports:
      - "9090-9095:8080"

volumes:
  kafka-vol:
#  db-mysql-vol:

networks:
  webhook-handler-network:
    driver: bridge