spring.application.name=requestHandler-service


spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Kafka

kafka-config.bootstrap-servers=${KAFKA_CONFIG_BOOTSTRAP_SERVERS}

kafka-producer-config.key-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka-producer-config.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

